feature
Sullynobugz/capstone-project pull request #9
Opened 2023-05-08 08:38 UTC by Sullynobugz

styling and shatter big component into smaller ones

2023-05-08 10:53 UTC, JessicaLoers reviewed
**Hey @Sullynobugz ✨** 
Aside from the comments I mentioned, I would like to make the following suggestions to you:

-  Please name your feature branches and your PRs more precisely in the future - this makes the code review much easier. 
- You could think about declaring your app colors as Custom Properties in your Global Styles. This will make it easier and faster to implement possible color changes in the future.
- It really pays to build a clean structure especially in the beginning, otherwise you'll drag the bugs from feature to feature with you and it will be more difficult and costly to refactor.
- Why do you use Arrow Functions instead of the function declaration? 
- Please check if all input elements have a label.
- Please do not pass Setter Function to components, but use the State Uplifting approach -  here is a Link zu the recommended Session Guides: [React Global State](https://github.com/neuefische/web-muc-23-1/blob/main/sessions/react-global-state/react-global-state.md), [React State 2 ](https://github.com/neuefische/web-muc-23-1/blob/main/sessions/react-state-2/react-state-2.md)
-  Please reconsider the file structure in the folder/component `Implimentation`. Each component folder should at best only contain the files of one component.

**There is still some work to be done, but it is worth it - promise 🤞**

2023-05-08 10:53 UTC, JessicaLoers commented on components/AddHabits/AddHabits.js
>      const newHabit = { id: Math.random().toString(), title: inputValue };
This is not part of the PR, but I would like to highly recommend you not to generate your IDs in this way.
Rather use a library like [uuid ](https://www.npmjs.com/package/uuid)

2023-05-08 10:53 UTC, JessicaLoers commented on components/AddHabits/AddHabits.js
>    }, []);
Again, this is not part of the PR, however I would like to mention that there is a **much handier and saver solution to storing your habits in Local Storage**.

Please have a look at the corresponding [session guide](https://github.com/neuefische/web-muc-23-1/tree/main/sessions/react-with-local-storage) again.

By the way, from a technical as well as a UI point of view, there is actually no need to store your data in local storage. 🫣

2023-05-08 10:53 UTC, JessicaLoers commented on components/AddHabits/AddHabits.js
> +    localStorage.setItem("habits", JSON.stringify([...habits, newHabit]));
Please see my comment below ✌️

2023-05-08 10:53 UTC, JessicaLoers commented on components/AddHabits/AddHabits.js
> +        <Input
For accessibility reasons: Please add a label to your input.

2023-05-08 10:53 UTC, JessicaLoers commented on components/AddHabits/AddHabits.js
>          </Link>
I don't see any reason to nest the link content in a div and inline styles aren't the best either. 🧐

Here is a solution: use a styled component for your link. 

**Example**
```
const StyledLink = styled(Link)`
 .... your styling declarations
`
```

2023-05-08 10:53 UTC, JessicaLoers commented on components/Implementation/HabitForm.js
> +`;
As mentioned before: I guess there is a slightly cleaner solution regarding your html structure ✌️

2023-05-08 10:53 UTC, JessicaLoers commented on components/Implementation/HabitForm.js
> +};
Please do not pass Setter Function directly to components, but use the State Uplifting approach.

2023-05-08 10:53 UTC, JessicaLoers commented on components/Implementation/HabitSelect.js
> +const HabitSelect = ({ habits, habit, setHabit }) => {
Please do not pass Setter Function directly to components, but use the State Uplifting approach.

2023-05-08 10:53 UTC, JessicaLoers commented on components/Implementation/ImplementationForm.js
> +const ImplementationForm = () => {
Please take another look at the guide to [Session JS Forms.](https://github.com/neuefische/web-muc-23-1/blob/main/sessions/js-forms/js-forms.md) 
I don't see any reason why you use controlled inputs - but maybe I'm missing something 🤷‍♀️

2023-05-08 10:53 UTC, JessicaLoers commented on components/Navbar/Navbar.js
> +          <DropdownLink onClick={() => handleNavigation("/implementation")}>
Why don't you use the [Next.j Link](https://nextjs.org/docs/pages/api-reference/components/link) component ?

2023-05-08 10:53 UTC, JessicaLoers commented on pages/index.js
>    };
Please delete this function because you don't use it.

2023-05-09 09:27 UTC, CJAkkuec requested changes

2023-05-09 09:27 UTC, CJAkkuec commented on components/AddHabits/AddHabits.js
>    }, []);
I'm going to second what @JessicaLoers has said since it hasn't been addressed in the updated PR. This isn't how we prefer to handle localStorage implementations. A localStorage implementation also doesn't appear to be part of the User Story. It would be difficult to test this as part of QA, because being able to create new habits and persisting them user-side via localStorage are two different features.

I'd strongly advise to not persist the habits at this point.

2023-05-10 07:28 UTC, merged